### ISSUE TITLE
Position of Class definition

### ISSUE THREAD

**Issue by DCEM** [turbo-meta/OOPEAu3#5] opened 2015-11-23 13:06 UTC
Testing AutoIt OOP Extender at the moment. 

Nice!

When I tried to run the demos i had to move the class definitons to the top otherwhise i would get the following error (example 05):
!> $oTest wants to be a Mouse object, but there is no class with that name!

After beeing on top of first use once i could put it back to the bottom.

Greetings,
David

**Comment by minxomat** [comment] 2015-11-24 16:40
Info: The demos are verified for 3.3.14.2 only. They are tested on a clean windows and AutoIt install, so I can't reproduce this error.

Did you alter the file in any way previous to running the example? Furthermore, are you able to create a minimal, self-contained example to demonstrate the issue you ran into?

**Comment by DCEM** [comment] 2015-11-25 15:12
Hello

Checked the Autoit version, it was still 3.3.14.1 
Did an upgrade the to 3.3.14.2 - but the errors still there - 

Tried the example 05 again: (file has not been changed so far)
!> $oTest wants to be a Mouse object, but there is no class with that name!
>Exit code: 76    Time: 0.1157

Then I marked the region:
#Region Class Mouse
#EndRegion

Copy and paste just before:
#classdef <Mouse> $oTest from <MouseGetPos()>

After that i get this error (expected):
Arguments.au3" (33) : ==> Duplicate function name.:
Func _Mouse($aArgs)

Here comes the funny part:
I remove the pasted area and after that it is running just fine, no errors at all.

**Comment by minxomat** [comment] 2015-11-25 19:54
Sounds to me like a privilege error. Make sure your user has write access to the demo directory and the AutoIt install directory.

**Comment by minxomat** [comment] 2015-12-06 19:43
I'm closing this for now since I can't repro. Discussion may continue.

**Closed by minxomat** 2015-12-06 19:43 UTC
Labels: question
